services:
    acme_vk.api_lib:
        class: Acme\VkBundle\Lib\VkApi

 #   acme_vk.default_controller:
 #       class: Acme\VkBundle\Controller\DefaultController
 #       arguments: ["@acme_vk.api_lib"]

    acme_vk.command.vk1:
          class: Acme\VkBundle\Command\VkParsing1Command
          arguments: ["@doctrine", "@acme_vk.api_lib", "@acme_main.collection_manager"]
          tags:
              -  { name: console.command }
