services:
#    acme_vk.example:
#        class: Acme\VkBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    acme_vk.command.vk1:
          class: Acme\VkBundle\Command\VkParsing1Command
          arguments: ["@doctrine"]
