Acme\VkBundle\Entity\VkAttachments:
    type: entity
    table: vk_attachments
    indexes:
        SECONDARY:
            columns:
                - announce_id
        moderator:
            columns:
                - moderator_id
        fk_attachments_3_idx:
            columns:
                - vk_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vkOwner:
            type: integer
            nullable: false
            unsigned: false
            column: vk_owner
        type:
            type: string
            nullable: false
            length: null
            fixed: false
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
        moderation:
            type: boolean
            nullable: false
            default: '0'
        moderationUpdated:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: moderation_updated
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
    manyToOne:
        announce:
            targetEntity: Announces
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                announce_id:
                    referencedColumnName: id
            orphanRemoval: false
        moderator:
            targetEntity: Moderators
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                moderator_id:
                    referencedColumnName: id
            orphanRemoval: false
        vk:
            targetEntity: VkUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                vk_id:
                    referencedColumnName: vk_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
