Acme\VkBundle\Entity\VkAttachments:
    type: entity
    table: vk_attachments
    indexes:
        announce_id:
            columns:
                - announce_id
        moderator:
            columns:
                - moderator_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vkOwner:
            type: integer
            nullable: false
            unsigned: false
            column: vk_owner
        type:
            type: string
            nullable: false
            length: null
            fixed: false
        src:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        srcBig:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: src_big
            default: ''
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        moderation:
            type: boolean
            nullable: false
            default: '0'
        moderationUpdated:
            type: datetime
            nullable: true
            default: '0000-00-00 00:00:00'
            column: moderation_updated
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        moderator:
            type: integer
            nullable: false
            column: moderator_id
    manyToOne:
        announce:
            targetEntity: \Acme\MainBundle\Entity\Announces
            inversedBy: attachments
            joinColumn:
                name: announce_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
