Acme\VkBundle\Entity\VkFriends:
    type: entity
    table: vk_friends
    indexes:
        friend:
            columns:
                - friend_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
    oneToOne:
        vkUser:
            targetEntity: VkUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                vk_id:
                    referencedColumnName: vk_id
            orphanRemoval: false
    manyToOne:
        vkFriend:
            targetEntity: VkUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                friend_id:
                    referencedColumnName: vk_id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
