Acme\VkBundle\Entity\VkParsingTasks:
    type: entity
    table: vk_parsing_tasks
    indexes:
        SECONDARY:
            columns:
                - vk_user_id
        isdone:
            columns:
                - is_done
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        level:
            type: boolean
            nullable: false
            default: '0'
        createdAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: updated_at
        isDone:
            type: boolean
            nullable: false
            default: '0'
            column: is_done
    manyToOne:
        vkUser:
            targetEntity: VkUsers
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            joinColumns:
                vk_user_id:
                    nullable: false
                    referencedColumnName: vk_id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
