Acme\VkBundle\Entity\VkParsingStat:
    type: entity
    table: vk_parsing_stat
    indexes:
        type:
            columns:
                - agr_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        agrType:
            type: string
            nullable: false
            length: null
            fixed: false
            column: agr_type
        level:
            type: boolean
            nullable: false
        count:
            type: integer
            nullable: false
            unsigned: false
        waiting:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
