services:
    acme_main.auth:
            class: Acme\MainBundle\Lib\Auth
            arguments: ["@doctrine", "@session"]

    kernel.listener.controller:
        class: Acme\MainBundle\EventListener\AuthListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: [@annotation_reader]
    kernel.listener.exception:
        class: Acme\MainBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }