Acme\MainBundle\Entity\Announces:
    type: entity
    table: Announces
    indexes:
        for_user_id:
            columns:
                - for_user_id
        moderator:
            columns:
                - moderator_id
        owner:
            columns:
                - owner_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sourceType:
            type: string
            nullable: false
            length: null
            fixed: false
            column: source_type
        ownerId:
            type: integer
            nullable: false
            unsigned: false
            column: owner_id
        postId:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: post_id
        friendId:
            type: integer
            nullable: false
            unsigned: false
            column: friend_id
        text:
            type: text
            nullable: false
            length: 65535
            fixed: false
        points:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        moderation:
            type: boolean
            nullable: false
            default: '0'
        moderationUpdated:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: moderation_updated
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        forUser:
            type: integer
            nullable: false
            column: for_user_id
        moderator:
            type: integer
            nullable: false
            column: moderator_id
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
