Acme\MainBundle\Entity\Announces:
    type: entity
    table: Announces
    indexes:
        for_user_id:
            columns:
                - for_user_id
        moderator:
            columns:
                - moderator_id
        owner:
            columns:
                - owner_id
        post_created:
            columns:
                - post_created_at
        copy_post_created:
            columns:
                - copy_post_created_at
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sourceType:
            type: string
            nullable: false
            length: null
            fixed: false
            column: source_type
        ownerId:
            type: integer
            nullable: false
            unsigned: false
            column: owner_id
        ownerPhoto:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            column: owner_photo
        postId:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: post_id
        copyOwnerId:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: copy_owner_id
        copyOwnerPhoto:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            column: copy_owner_photo
        copyPostId:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: copy_post_id
        friendId:
            type: integer
            nullable: false
            unsigned: false
            column: friend_id
        text:
            type: text
            nullable: false
            length: 65535
            fixed: false
        points:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        moderation:
            type: boolean
            nullable: false
            default: '0'
        moderationUpdated:
            type: datetime
            nullable: true
            default: '0000-00-00 00:00:00'
            column: moderation_updated
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        forUserId:
            type: integer
            nullable: false
            column: for_user_id
        moderator:
            type: integer
            nullable: false
            column: moderator_id
        postCreatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: post_created_at
        copyPostCreatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: copy_post_created_at
    oneToMany:
        attachments:
            targetEntity: \Acme\VkBundle\Entity\VkAttachments
            mappedBy: announces
            joinColumn:
                name: id
                referencedColumnName: announce_id
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
