Acme\MainBundle\Entity\Announces:
    type: entity
    repositoryClass: Acme\MainBundle\Entity\AnnouncesRepository
    table: Announces
    indexes:
        moderator:
            columns:
                - moderator_id
        owner:
            columns:
                - owner_id
        postCreated:
            columns:
                - post_created_at
    uniqueConstraints:
        post:
            columns:
                - owner_id
                - post_id
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        sourceType:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: source_type
        ownerId:
            type: integer
            nullable: false
            column: owner_id
        postId:
            type: integer
            nullable: false
            default: '0'
            column: post_id
        text:
            type: text
            nullable: false
            length: 65535
            fixed: false
        points:
            type: integer
            nullable: false
            default: '0'
        moderation:
            type: boolean
            nullable: false
            default: '0'
        moderationUpdated:
            type: datetime
            nullable: true
            default: '0000-00-00 00:00:00'
            column: moderation_updated
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        moderator:
            type: integer
            nullable: false
            column: moderator_id
        postCreatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: post_created_at
    oneToMany:
        attachments:
            targetEntity: \Acme\VkBundle\Entity\VkAttachments
            mappedBy: announce
            joinColumn:
                name: id
                referencedColumnName: announce_id
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
