Acme\MainBundle\Entity\Moderators:
    type: entity
    table: moderators
    indexes:
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
        pass:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        rules:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
