Acme\MainBundle\Entity\Moderators:
    type: entity
    table: moderators
    indexes:
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 70
            fixed: false
        pass:
            type: string
            nullable: false
            length: 45
            fixed: false
        rules:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
