Acme\MainBundle\Entity\Subscriptions:
    type: entity
    table: subscriptions
    indexes:
        email:
            columns:
                - email
    uniqueConstraints:
        SECONDARY:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 70
            fixed: false
        isActive:
            type: boolean
            nullable: false
            default: '1'
            column: is_active
        createdAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        user:
            type: integer
            nullable: false
            default: 0
            column: user_id
    lifecycleCallbacks:
        prePersist: [doStuffOnPrePersist]
